version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    container_name: web
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
