version: '3.8'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: node-api
    volumes:
      - ./server:/app
      - /app/node_modules
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    command:
      npm start
    ports:
      - "3000:3000"   
    volumes:
      - ./frontend:/app
    stdin_open: true  
